name: aparna_pod
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+4

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  injectable: ^2.5.1
  flutter_bloc: ^9.1.1
  animated_custom_dropdown: ^3.1.1
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  google_fonts: ^6.3.0
  dartz: ^0.10.1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.7
  logger: ^2.6.2
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  get_it: ^8.3.0
  http: ^1.6.0
  image_picker: ^1.1.2
  go_router: ^15.1.2
  url_launcher: ^6.3.1
  photo_view: ^0.12.0
  simple_barcode_scanner: ^0.3.0
  connectivity_plus: ^6.0.2
  file_picker: 8.1.4
  package_info_plus: ^9.0.0
  google_mlkit_text_recognition: ^0.15.0
  freezed: ^2.4.7 
  flutter_image_compress: ^2.4.0
  image: ^4.5.4
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_launcher_icons: ^0.14.4
  image_cropper: ^11.0.0
  cunning_document_scanner: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/logo/

flutter_launcher_icons: 
  android: 'ic_launcher'
  image_path: 'assets/logo/aparna.png'
  min_sdk_android: 21 