name: aparna_pod
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  injectable: ^2.5.1
  flutter_bloc: ^9.1.1
  animated_custom_dropdown: ^3.1.1
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  google_fonts: ^6.3.0
  dartz: ^0.10.1
  freezed_annotation: ^3.1.0
  equatable: ^2.0.7
  logger: ^2.6.2
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  package_info_plus: ^9.0.0
  get_it: ^8.3.0
  http: ^1.6.0
  image_picker: ^1.1.2
  go_router: ^15.1.2
  url_launcher: ^6.3.1
  photo_view: ^0.15.0
  simple_barcode_scanner: ^0.3.0
  connectivity_plus: ^6.0.2
  file_picker: 8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  injectable_generator: ^2.6.2
  freezed: ^3.0.0-0.0.dev

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
